<a href="https://colab.research.google.com/github/Khaydaraliev/amaliyot_ishlari_mohirdev/blob/main/mohirdev_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [2]:
import numpy as np

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [3]:
list  = [1,2,3,4,5]
array = np.array(list)
print(f"list : {list}")
print(f"array : {array}")

list : [1, 2, 3, 4, 5]
array : [1 2 3 4 5]


#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [4]:
shape = (9)
zero_array = np.zeros(shape)
print(zero_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [5]:
shape = (25, 27)
arr = np.zeros(shape)
print(f"size : {arr.size}")
print(f"itemsize : {arr.itemsize}")

size : 675
itemsize : 8


#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [6]:
np.info(np.add)

# yoki

#np.info('add')

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [7]:
vek_arr = np.zeros(12)
vek_arr[5] = 1
print(vek_arr)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [8]:
vek_a = np.arange(20 , 60)
print(vek_a)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [9]:
vek_b = np.arange(10)
vek_b = vek_b[::-1]
print(vek_b)

[9 8 7 6 5 4 3 2 1 0]


#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [10]:
a = np.arange(12,21)
matrix = a.reshape(3,3)
print(matrix)

[[12 13 14]
 [15 16 17]
 [18 19 20]]


#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [11]:
matritsa = np.array([3, 7, 0, 0, 9, 0])
index_val_notzero = np.nonzero(matritsa)
print(f"Indices of non-zero elements : {index_val_notzero}")

Indices of non-zero elements : (array([0, 1, 4]),)


#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [12]:
arr_ran = np.random.random((2,2,2))
print(arr_ran)

[[[8.05979791e-01 4.72867479e-04]
  [8.54591407e-01 3.17553076e-02]]

 [[3.01300321e-01 1.96049090e-01]
  [7.52947416e-01 3.15010750e-01]]]


#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [13]:
arr_ran1 = np.random.random((9,9))
max = np.amax(arr_ran1)
min = np.amin(arr_ran1)
print(f"Array : \n{arr_ran1}\nmax value : {max}\nmin value : {min}")

Array : 
[[0.64475546 0.38800564 0.08286299 0.98432928 0.04793949 0.70851158
  0.47073493 0.91461817 0.37562833]
 [0.55542503 0.34001105 0.61338648 0.92723539 0.09433599 0.76274902
  0.39959769 0.70314148 0.89188389]
 [0.71002532 0.9131837  0.42631113 0.92256481 0.79387379 0.28039589
  0.82942377 0.04631954 0.26548222]
 [0.15235875 0.33664032 0.8435369  0.74166526 0.55518688 0.07055901
  0.17141539 0.66621793 0.01421724]
 [0.95824332 0.44175607 0.12930429 0.78366866 0.03547679 0.79979857
  0.79469349 0.94421497 0.49030488]
 [0.68776416 0.20765359 0.72534716 0.70818381 0.91004258 0.74718504
  0.78899882 0.25943387 0.29198971]
 [0.12011418 0.19543633 0.93582985 0.96409834 0.87452938 0.89823462
  0.41800651 0.49488852 0.96509121]
 [0.57099268 0.60841756 0.543978   0.53168102 0.17611924 0.27154467
  0.95421169 0.33445078 0.82861534]
 [0.83295728 0.20883376 0.77789271 0.85950688 0.36477788 0.26389787
  0.10978095 0.4414325  0.33093499]]
max value : 0.984329279942796
min value : 0.0142172384

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [14]:
#(NaN, False, False, NaN, True, False)
result1 = 0 * np.nan
result2 = np.nan == np.nan
result3 = np.inf > np.nan
result4 = np.nan - np.nan
result5 = np.nan in set([np.nan])
result6 = 0.7 == 7 * 0.1

print("Result 1: ", result1)
print("Result 2: ", result2)
print("Result 3: ", result3)
print("Result 4: ", result4)
print("Result 5: ", result5)
print("Result 6: ", result6)


Result 1:  nan
Result 2:  False
Result 3:  False
Result 4:  nan
Result 5:  True
Result 6:  False


#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [15]:
arr_1 = np.random.random((6,3))
arr_2 = np.random.random((3,4))
multi = np.dot(arr_1, arr_2)
mul= np.concatenate((arr_1, arr_2), axis=None)
print(multi)
print(mul)

[[0.32890307 0.86961892 0.68291924 0.77053312]
 [0.56824015 1.11011097 0.9663251  0.96732876]
 [0.56060856 1.32255377 0.98030489 1.01876805]
 [0.61315519 0.33908224 0.98026602 0.86001289]
 [0.27350201 0.67291066 0.59800204 0.68108765]
 [0.5545626  1.14740476 0.90607787 0.89473483]]
[0.83704197 0.03407365 0.29655387 0.70116207 0.40763399 0.65061315
 0.90155574 0.25180504 0.77961912 0.05437157 0.98672419 0.09308392
 0.73239519 0.04226262 0.13498017 0.64115661 0.37932597 0.77407606
 0.30752017 0.7708419  0.74532775 0.87765737 0.5880905  0.23230564
 0.9438315  0.82069872 0.17351784 0.72997325 0.09067101 0.02675017]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [16]:
# Natija 10 ga teng.
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [17]:
a = np.arange(12).reshape(3,4)
b = np.arange(13,25).reshape(3,4)

com_1 = a > b
print(com_1)
com_2 = a >= b
print(com_2)
com_3 = a < b
print(com_3)
com_4 = a <= b
print(com_4)

[[False False False False]
 [False False False False]
 [False False False False]]
[[False False False False]
 [False False False False]
 [False False False False]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [18]:
# Natija : NaN , NaN , 0
NaN
NaN
0

0

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [19]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

common_values = np.intersect1d(array1, array2)
print("Common values:", common_values)

Common values: [3 4 5]


#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [20]:
random_array = np.random.randn(10)
# (%)
mus_son_1 = random_array[random_array > 0]
#  np.floor
mus_son_floor = random_array[np.floor(random_array) > 0]
#  astype
mus_son_astype = random_array[random_array.astype(int) > 0]
#  np.trunc
mus_son_trunc = random_array[np.trunc(random_array) > 0]

print("Array:", random_array)
print("Musbat sonlar(%):", mus_son_1)
print("Musbat sonlar(np.floor):", mus_son_floor)
print("Musbat sonlar(astype):", mus_son_astype)
print("Musbat sonlar(np.trunc):", mus_son_trunc)


Array: [-0.28985193 -0.09609382  0.46121081  0.39311069 -0.51839802  1.57069096
 -0.49443731  0.0877854   0.63518861 -0.34765972]
Musbat sonlar(%): [0.46121081 0.39311069 1.57069096 0.0877854  0.63518861]
Musbat sonlar(np.floor): [1.57069096]
Musbat sonlar(astype): [1.57069096]
Musbat sonlar(np.trunc): [1.57069096]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [21]:
matrix = np.random.randint(0, 3, size=(3, 3))
print(matrix)

[[2 1 0]
 [2 0 1]
 [2 0 1]]


#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [22]:
vector = np.random.rand(10)
sort_vec = np.sort(vector)
print("vector:", vector)
print("sort_vec:", sort_vec)

vector: [0.07910432 0.66547376 0.10182007 0.37656472 0.08519473 0.42851972
 0.45074202 0.97934069 0.2620982  0.47762935]
sort_vec: [0.07910432 0.08519473 0.10182007 0.2620982  0.37656472 0.42851972
 0.45074202 0.47762935 0.66547376 0.97934069]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [23]:
array1 = np.random.rand(10)
array2 = np.random.rand(10)
b_1 = np.allclose(array1, array2)
b_2 = np.array_equal(array1, array2)
print(b_1 , b_2)

False False


#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [24]:
mat_1 = np.random.randint(10, size=(6, 3))
mat_2 = np.random.randint(10, size=(3, 4))
mult = np.dot(mat_1 , mat_2)
print(f"mat_1 : \n{mat_1}\nmat_2 : \n{mat_2}\nmult : \n{mult}")

mat_1 : 
[[3 5 2]
 [0 4 8]
 [0 2 6]
 [1 8 3]
 [2 2 9]
 [5 3 6]]
mat_2 : 
[[3 0 7 4]
 [3 9 5 5]
 [4 2 2 7]]
mult : 
[[32 49 50 51]
 [44 52 36 76]
 [30 30 22 52]
 [39 78 53 65]
 [48 36 42 81]
 [48 39 62 77]]


#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [25]:
vector = np.random.rand(5)
max_index = np.argmax(vector)
print("Max value",vector[max_index])
vector[max_index] = 0
print("Max value index:", max_index)
print("Vector:", vector)


Max value 0.7830656548068117
Max value index: 4
Vector: [0.05543333 0.753794   0.67810939 0.57248927 0.        ]


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [26]:
from datetime import datetime, timedelta

kecha = (datetime.now() - timedelta(days=1)).day
bugun = datetime.now().day
ertaga = (datetime.now() + timedelta(days=1)).day

print("Kecha:", kecha)
print("Bugun:", bugun)
print("Ertaga:", ertaga)

Kecha: 11
Bugun: 12
Ertaga: 13


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [27]:
sanalar = np.arange('2016-01-01', '2016-02-01', dtype='datetime64[D]')

print(sanalar)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [30]:
musbat_massiv = np.random.rand(10)*10

butun_sonlar_modul = musbat_massiv - musbat_massiv % 1

butun_sonlar_floor = np.floor(musbat_massiv)

butun_sonlar_astype = musbat_massiv.astype(int)

butun_sonlar_trunc = np.trunc(musbat_massiv)

print("Tasodifiy musbat sonlar:", musbat_massiv)
print("Modul operatori (%):", butun_sonlar_modul)
print("np.floor():", butun_sonlar_floor)
print("astype(int):", butun_sonlar_astype)
print("np.trunc():", butun_sonlar_trunc)


Tasodifiy musbat sonlar: [4.58221217 0.24728503 5.41185942 5.37619705 5.26168893 8.42320535
 0.96619226 7.65141711 0.71068378 9.73203624]
Modul operatori (%): [4. 0. 5. 5. 5. 8. 0. 7. 0. 9.]
np.floor(): [4. 0. 5. 5. 5. 8. 0. 7. 0. 9.]
astype(int): [4 0 5 5 5 8 0 7 0 9]
np.trunc(): [4. 0. 5. 5. 5. 8. 0. 7. 0. 9.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [32]:
arr = np.array([1, 2, 3, 4, 5])
mass = np.add.reduce(arr)
print("Yig'indi:", mass)

Yig'indi: 15


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [34]:
vektor = np.array([1, 2, 3, 4, 5])
result_vektor = np.zeros(len(vektor) * 4, dtype=int)
result_vektor[::4] = vektor
print("Boshlang'ich vektor:", vektor)
print("O'zgartirilgan vektor:", result_vektor)

Boshlang'ich vektor: [1 2 3 4 5]
O'zgartirilgan vektor: [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [38]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
b = np.array([a[i:i+4] for i in range(len(a)-3)])
print("B massivi:", b)


from numpy.lib.stride_tricks import as_strided
c = as_strided(a, shape=(11, 4), strides=(a.itemsize, a.itemsize))
print("C massivi:", c)

B massivi: [[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
C massivi: [[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [39]:
massiv = np.random.randint(0, 10, size=20)
print("Ixtiyoriy sonlar massivi:", massiv)
counter = np.bincount(massiv)
max_value = np.argmax(counter)
print("Eng ko'p uchrashgan qiymat:", max_value)

Ixtiyoriy sonlar massivi: [3 9 1 3 2 6 8 4 3 9 8 3 2 8 2 0 5 6 3 4]
Eng ko'p uchrashgan qiymat: 3


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`